### ISSUE TITLE
Rover URDF connection problems

### ISSUE THREAD

**Issue by iitb-martian** [iitbmartian/GUI#1]
The differential mechanism doesn't seem to be connected to the rocker.

![bug](https://cloud.githubusercontent.com/assets/25772881/22940055/a882d96e-f306-11e6-89a4-58d05fae872c.png)

**Comment by iitb-martian** [comment]
If I insert an asphalt plane beneath the rover, the chassis rotates about the pin joints connecting it to the rover-bogie.

**Comment by robodhruv** [comment]
If I remember right, this had to be left so because URDF does not support loops in the graph. The links should form a valid tree.
@Agrim9 any updates?

**Comment by alankarkotwal** [comment]
@Agrim9 proposes splitting the link in between the differential triangles on
both sides and constraining the two pieces.

**Comment by Agrim9** [comment]
Issue still remains in 2016-17 URDF due to limitations in loops of URDF. The primary URDF now is ASPHA18 URDF
